// Pack index generation: topic-packs/INDEX.md is the committed, grep-shaped
// search surface for community content (skills search it offline before
// generating anything). Deterministic, so validate can check freshness.
// Usage: node tools/packs.ts [--check]
import { fileURLToPath } from 'node:url';
import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { parseFrontmatter } from '../lib/frontmatter.ts';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));

interface PackEntry {
  domain: string;
  slug: string;
  title: string;
  audience: string;
  hours: string;
  objectives: string[];
}

export function collectPacks(packsRoot: string): PackEntry[] {
  const out: PackEntry[] = [];
  if (!existsSync(packsRoot)) return out;
  for (const domain of readdirSync(packsRoot).sort()) {
    const domainDir = join(packsRoot, domain);
    if (!statSync(domainDir).isDirectory()) continue;
    for (const slug of readdirSync(domainDir).sort()) {
      const packDir = join(domainDir, slug);
      const courseFile = join(packDir, 'course.yml');
      if (!existsSync(courseFile)) continue;
      const course = parseYaml(readFileSync(courseFile, 'utf8')) as {
        title?: string;
        objectives?: { text: string }[];
      };
      const packMd = join(packDir, 'PACK.md');
      const fm = existsSync(packMd) ? parseFrontmatter(readFileSync(packMd, 'utf8')).frontmatter : null;
      out.push({
        domain,
        slug,
        title: String(course.title ?? slug),
        audience: String(fm?.audience ?? 'unstated'),
        hours: String(fm?.hours ?? 'unstated'),
        objectives: (course.objectives ?? []).map((o) => o.text),
      });
    }
  }
  return out;
}

export function buildIndex(packsRoot: string): string {
  const packs = collectPacks(packsRoot);
  const lines = [
    '# Pack index',
    '',
    '*Generated by `node tools/packs.ts` - do not edit by hand. Skills grep this file to*',
    '*search community coverage before generating anything new.*',
    '',
  ];
  for (const p of packs) {
    lines.push(`## ${p.domain}/${p.slug} - ${p.title}`);
    lines.push('');
    lines.push(`Audience: ${p.audience}. Hours: ${p.hours}.`);
    lines.push('');
    for (const o of p.objectives) lines.push(`- ${o}`);
    lines.push('');
  }
  if (packs.length === 0) lines.push('No packs yet.', '');
  return lines.join('\n');
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const packsRoot = join(repoRoot, 'topic-packs');
  const indexPath = join(packsRoot, 'INDEX.md');
  const fresh = buildIndex(packsRoot);
  if (process.argv.includes('--check')) {
    const current = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : '';
    if (current === fresh) {
      console.log('INDEX.md is fresh');
    } else {
      console.error('INDEX.md is stale - run `node tools/packs.ts`');
      process.exit(1);
    }
  } else {
    writeFileSync(indexPath, fresh);
    console.log(`wrote ${indexPath}`);
  }
}
